# Medium utf8properties project with multiple documents and translations

PRJ_TYPE:=utf8properties
SLUG:=guvnor
NAME:="Guvnor"
DESC:="Guvnor is the web application and repository to govern Drools and jBPM assets."
VERS:=master 6.0.x 5.6.x
REPO_TYPE:=git
URL:=git://github.com/droolsjbpm/$(SLUG).git
INCLUDES:="**/src/main/**/*Constants.properties"

include ../common.mk

