# Small podir project with translations

PRJ_TYPE:=podir
SLUG:=man-pages-l10n
NAME:="man-pages-l10n"
DESC:="localized man pages"
VERS:=master
REPO_TYPE:=git
URL:=https://git.fedorahosted.org/git/$(SLUG).git
SRC_DIR:=pot
TRANS_DIR:=po

include ../common.mk

