# Small podir project with translations

PRJ_TYPE:=podir
SLUG:=about-fedora
NAME:="About Fedora"
DESC:="Fedora document About Fedora"
VERS:=master f13 f11
REPO_TYPE:=git
URL:=git://git.fedorahosted.org/git/docs/$(SLUG).git

include ../common.mk

