RUN curl -O https://repos.fedorapeople.org/repos/dchen/epel-collection/epel-epel-collection.repo; yum -y update; yum sudo git glibc-common; yum clean all
RUN cat > /etc/profile.d/common.sh<<<'export PS1="[\u@\h \w]\\$ "'
##Disable Defaults requiretty in sudoers file
RUN sed -ie 's/Defaults\\(.*\\)requiretty/ #Defaults\\1requiretty/g' /etc/sudoers
RUN groupadd sudo; echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

