# Small File project with translations

SLUG=freemind-doc
NAME="freemind Documentation"
DESC="Documentation of freemind"
VERS=0.9.0
PRJ_TYPE=file

all: download_vers

download_vers:

clean:
	rm -fr ${VERS}
