#!/bin/bash

# add any locales that aren't present

INSERTPRE="insert ignore into HLocale (localeId, creationDate, lastChanged, active) values ('"
INSERTPOST="', now(), now(), 1);"

#echo This script needs the mysql root password.
#NOTE: if you have a mysql root password set, add a -p flag to this command and
#      enter it when running the script

#NOTE: this should be disabled if pushing to a server other than localhost
#mysql -u root<<-EOFMYSQL
#    use zanata
#    ${INSERTPRE}en-US${INSERTPOST}
#    ${INSERTPRE}ja${INSERTPOST}
#    ${INSERTPRE}ru${INSERTPOST}
#    ${INSERTPRE}zh${INSERTPOST}
#EOFMYSQL


#TODO make sure you set up the username and api key for any server you use in
#     ~/.config/zanata.ini

#change these to run tests against different servers
#SERVER="http://localhost:8080/zanata/"
#SERVER="http://zanata-endeavour.lab.eng.bne.redhat.com:8080/"
SERVER="http://zanata-empire.lab.eng.bne.redhat.com:8080/"

PROJECT="copytrans-test-project-4"
PROJNAME=$PROJECT
PROJDESC=$PROJECT


# old keys, some still valid, others overridden below
URLKEY=zanata.url
PKEY=zanata.project
PSKEY=zanata.project.slug
PNKEY=zanata.project.name
PDKEY=zanata.project.desc
VPKEY=zanata.version.project
PVKEY=zanata.projectVersion
VSKEY=zanata.version.slug
CTKEY=zanata.copyTrans
PTKEY=zanata.pushTrans


# Looks like these changed for 1.5
# TODO comment out or make a switch to build with old keys
PSKEY=zanata.projectSlug
PNKEY=zanata.projectName
PDKEY=zanata.projectDesc
VPKEY=zanata.versionProject
VSKEY=zanata.versionSlug




PROJVEROPTS="-D${URLKEY}=${SERVER}"
PUTPROJOPTS="${PROJVEROPTS} -D${PSKEY}=${PROJECT} -D${PNKEY}=${PROJNAME} -D${PDKEY}=${PROJDESC}"
PUTVEROPTS="${PROJVEROPTS} -D${VPKEY}=${PROJECT}"
VEROPT="-D${PVKEY}="
SLUGOPT="-D${VSKEY}="

PUSHOPTS="-D${URLKEY}=${SERVER} -D${PKEY}=${PROJECT}"
PUSH="mvn zanata:push -B ${PUSHOPTS}"
PUSHTRANSOPT="-D${PTKEY}=true"

# Swap to 'false' to run benchmark without copytrans for comparison
#COPYOPT="-Dzanata.copyTrans=false"
COPYOPT="-D${CTKEY}=true"

TEST="[LOAD TEST]"

cd v1
mvn zanata:putproject $PUTPROJOPTS
cd ..

for VERSION in v1 v2 v3 v4 v5
do
    echo 
    echo $TEST preparing to push $VERSION
    cd $VERSION
    mvn zanata:putversion $PUTVEROPTS $VEROPT$VERSION $SLUGOPT$VERSION
    echo
    echo $TEST pushing $VERSION without translations
    time $PUSH $VEROPT$VERSION $COPYOPT
    echo $TEST pushed $VERSION
    if [ "$VERSION" != "v5" ]; then #don't push translations for the final version
        echo
        echo $TEST now pushing $VERSION with translations - should not trigger copyTrans
        time $PUSH $PUSHTRANSOPT $VEROPT$VERSION $COPYOPT
        echo $TEST pushed $VERSION translations
    fi
    cd ..
done
echo $TEST TEST COMPLETE
