# Small File project with translations

SLUG=freemind-doc
NAME="freemind Documentation"
DESC="Documentation of freemind"
VERS=0.9.0
PRJ_TYPE=file

download_all:
	echo "Already in source control"

clean:
	rm -fr ${VERS}
