# Small File project with translations

PRJ_TYPE:=file
SLUG:=freemind-doc
NAME:="freemind Documentation"
DESC:="Documentation of freemind"
VERS:=0.9.0

download_all:
	echo "Already in source control"

clean:
	echo "Already in source control"

